### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by skyluc** [scala-ide/uber-build#48]
To follow the progress of the different changes needed for the support of Scala 2.12
- [x] support in sbinary harrah/sbinary#14
- [x] support in sbt sbt/sbt#1396
- [ ] support in uber-build to produce zinc nightlies for 2.12 #49
- [x] nightly build to publish zinc on 2.12
- [ ] update zinc nightly to use uber-build/master
- [x] support in scalariform daniel-trinh/scalariform#23 daniel-trinh/scalariform#24
- [x] nightly build to publish scalariform on 2.12
- [x] update scalariform nightly to use daniel-trinh/0.1.6-SNAPSHOT
- [x] update scalariform nightly build symlink when using 'master' branch (scalariform-212x)
- [x] support in scala-refactoring
- [x] nightly build to publish scala-refactoring on 2.12
- [ ] support in Scala IDE scala-ide/scala-ide#727
- [ ] add build on 2.12 for Scala IDE pr validation
- [x] add nightly build for Scala IDE on 2.12
- [ ] update scala-ide nightly to use scala-ide/master
- [ ] update Scala IDE nightly build symlink when using 'master' branch (nightly-scala-ide-4.0.x-212x)
- [x] support in plugin-profiles scala-ide/plugin-profiles#4
- [x] release plugin-profiles
- [ ] support in scala-worksheet [2.12-support](https://github.com/skyluc/scala-worksheet/tree/2.12-support) requires new version of plugin-profiles
- [ ] add nightly build for scala-worksheet on 2.12
- [ ] support in scala-search [2.12-support](https://github.com/skyluc/scala-search/tree/2.12-support) requires new version of plugin-profiles
- [ ] add nightly build for scala-search on 2.12
- [ ] create composite update site for nightlies 2.12
- [ ] support in uber-build [scala-2.12](https://github.com/skyluc/uber-build/tree/scala-2.12)
- [ ] add nightly build for the uber-build
- [ ] support in build-tools ?
- [ ] support in ecosystem ?
- [ ] re-enable Scala IDE build in scala-pr-validator for Scala 2.12

**Comment by retronym** [comment]
#49 is merged, shall we cross if off this list? Any other items that we could tick off?

**Comment by adriaanm** [comment]
Looks like 2.10.x also hasn't built successfully (first failure: scala/scala#4186, https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/9174/console)

**Comment by retronym** [comment]
@sschaef @dragos We'd like to prioritize this work so that we can aim to have IDE building with Scala 2.12.0-M5 ([scheduled](https://github.com/scala/scala/milestones) April 25).

Is the big list above still an accurate reflection of the status of the work? Are there any shortcuts that could be taken as intermetiate steps to get at least the core building, e.g. building a slimmer IDE without worksheet, Scalatest, scala-search etc? What help do you need from the Scala team?

**Comment by sschaef** [comment]
The CI build doesn't build any of the plugins, they are only important for a release version. Beside of a few possible source incompatibilities with scalac I don't think that we run in further issues for the scala-ide core. I were looking in updating uber-build for the 2.11 CI integration anyway in the last days. After that is completed I can have a look about what needs to be done for the 2.12 version and then update this ticket.

**Comment by retronym** [comment]
Thanks for the update, looking forward to hear what you find out!

**Comment by dragos** [comment]
I think the list is accurate. The biggest problem was that there is no scala-actors for 2.12. I think we don't use them anymore, but there's still a dependency on scala actors in pom files, I think.

**Comment by sschaef** [comment]
On 01/20/2016 11:31 AM, Iulian Dragos wrote:
>
> but there's still a dependency on scala actors in pom files, I think.
>
No, scala-actors is completely gone.

**Comment by benmccann** [comment]
@skyluc It looks like we can cross off https://github.com/scala-ide/uber-build/pull/49 and https://github.com/scala-ide/scala-ide/pull/727. Can you cross those off on your list?

What's the next ticket in order that should be addressed?

**Comment by benmccann** [comment]
@sschaef thanks for updating! So this is fixed then? Is there anything else needed for Scala 2.12 support in Scala IDE?

**Comment by sschaef** [comment]
We are working on the last remaining bits. We will inform you through the mailing lists once a nightly for 2.12 is available.
